// @ts-nocheck
// mkfinder.mts — writes finder.sql (reviewer's READ-ONLY forensic query) from the pattern validated in sqlcheck.mts
import { writeFileSync } from "node:fs";
const SEP = "(\\s|&[a-z]+;?|&#0*[0-9]+;?|&#x0*[0-9a-f]+;?)*";
const L = (ch: string) => { const u = ch.toUpperCase().charCodeAt(0), l = ch.toLowerCase().charCodeAt(0); return `(${ch}|&#0*(${l}|${u});?|&#x0*(${l.toString(16)}|${u.toString(16)});?)`; };
const word = (w: string) => [...w].map(L).join(SEP) + SEP + "(:|&colon;?|&#0*58;?|&#x0*3a;?)";
export const RE = "<[a-z][^\\s>/]*/|<[a-z][a-z0-9]*[-:]|<(svg|math|details|video|audio|body|iframe|frame|object|embed|form|input|button|select|textarea|marquee|meta|base|link|style|script|img|template|isindex|xmp|noembed|noframes|plaintext|title)[\\s/>]|[\\s/\"'`]on[a-z]+\\s*=|" + word("javascript") + "|" + word("vbscript") + "|data:";
const lit = (s: string) => "'" + s.replace(/'/g, "''") + "'";
const sql = `-- finder.sql — READ-ONLY forensic finder for stored HTML that the PRE-hotfix code rendered as live markup
-- (reviewer version of the query in ledger/wo-notes/hotfix-sanitize-2026-10-01.md; generated by scripts/pending/hsan-review/mkfinder.mts,
--  pattern recall measured in sqlcheck.mts: 0 misses on 103 027 legacy-sanitised + RAW samples, vs 37/27/447 for the note's pattern).
-- Safe on production at business hours: one READ ONLY transaction (writes impossible), statement timeout, AccessShareLock only
-- (never blocks INSERT/UPDATE), LIMIT per table. Seq-scans the three small tables. CrmEmailMessage part = separate, off-peak, 90-day window.
-- Matches are SUSPICIOUS, not proof: expect noise from <br/>, <o:p>, "data:" in prose. Look at the "hit" column first.
BEGIN READ ONLY;
SET LOCAL statement_timeout = '60s';
WITH p AS (SELECT ${lit(RE)}::text AS re)
SELECT * FROM (
  (SELECT 'MemberPrivacyPolicy' AS tbl, t.id, t."tenantId", t."createdAt", substring(t."bodyHtml" from '(?i)(' || p.re || ')') AS hit, left(t."bodyHtml", 200) AS sample
     FROM "MemberPrivacyPolicy" t, p WHERE t."bodyHtml" ~* p.re ORDER BY t."createdAt" DESC LIMIT 500)
  UNION ALL
  (SELECT 'KanbanCard', t.id, t."tenantId", t."createdAt", substring(t.description from '(?i)(' || p.re || ')'), left(t.description, 200)
     FROM "KanbanCard" t, p WHERE t.description ~* p.re ORDER BY t."createdAt" DESC LIMIT 2000)
  UNION ALL
  (SELECT 'KanbanCardTemplate', t.id, t."tenantId", t."createdAt", substring(t.description from '(?i)(' || p.re || ')'), left(t.description, 200)
     FROM "KanbanCardTemplate" t, p WHERE t.description ~* p.re ORDER BY t."createdAt" DESC LIMIT 500)
) x ORDER BY tbl, "createdAt" DESC;
ROLLBACK;

-- informational, OFF-PEAK (bodies can be MBs; sandboxed viewer, but REST thread reads return bodyHtml raw):
BEGIN READ ONLY;
SET LOCAL statement_timeout = '120s';
SELECT 'CrmEmailMessage' AS tbl, id, "tenantId", "createdAt", substring("bodyHtml" from '(?i)(' || ${lit(RE)} || ')') AS hit
  FROM "CrmEmailMessage"
 WHERE "createdAt" > now() - interval '90 days' AND "bodyHtml" ~* ${lit(RE)}
 ORDER BY "createdAt" DESC LIMIT 200;
ROLLBACK;
`;
writeFileSync(new URL("./finder.sql", import.meta.url), sql);
console.log(`finder.sql written (${sql.length} bytes, pattern ${RE.length} chars)`);
